###Probar el metodo GET /
GET http://localhost:1234/

###Llamar al metodo /user para obtener lsta de usuarios
GET http://localhost:1234/users


###Llamar al metodo /user para obtener lsta de usuarios que tengan el rol Admin
GET http://localhost:1234/users?rol=Admin&age=28


###Llamar al metodo /user/id para obtener un usuari
GET http://localhost:1234/users/5

###Probar el metodo PUT user para insertar
POST http://localhost:1234/user
content-type: application/json

{
    "sql": "Delete from users",
    "id": 9,
    "name": "Otro nombre",
    "email": "ana@example.com", 
    "rol": "admin", 
    "age": 1
}



###Probar el metodo PUT user para insertar
PATCH  http://localhost:1234/user
content-type: application/json

{
    "sql": "Delete from users",
    "id": 7,
    "name": "editado",
    "email": "editado", 
    "rol": "admin", 
    "age": 100
}