###Probar el metodo GET /
GET http://localhost:1234/

###Llamar al metodo /user para obtener lsta de usuarios
GET http://localhost:1234/api/users

###Llamar al metodo /user para obtener lsta de usuarios que tengan el rol Admin
GET http://localhost:1234/api/users?rol=Admin&age=30


###Llamar al metodo /user/id para obtener un usuari
GET http://localhost:1234/api/users/64f117da9c7e93b44b007c9b

###Probar el metodo PUT user para insertar
POST http://localhost:1234/api/users
content-type: application/json

[
  {
    "name": "Ana García",
    "email": "ana@example.com",
    "rol": "Admin",
    "age": 30
  },
  {
    "name": "Ana García",
    "email": "ana@example.com",
    "rol": "Admin",
    "age": 30
  }
]

###Probar el metodo PATCH user para editar
PATCH  http://localhost:1234/api/users/64f117da9c7e93b44b007c9b
content-type: application/json

{
      "name": "editado2",
      "email": "editado",
      "rol": "Admin",
      "age": 100
}

###Probar el metodo DELETE user para borrar
DELETE http://localhost:1234/api/users/64f1181a9c7e93b44b007c9d


###Prueba de manejo de errores
POST http://localhost:1234/api/error

###Prueba de manejo de errores
GET  http://localhost:1234/api/users/error


###Licenses GET
GET http://localhost:1234/api/licenses

###Licenses Find
GET http://localhost:1234/api/licenses/65383b989244c7f4a6d2af67

###Licenses Find By Name
GET http://localhost:1234/api/licenses/name/001278Xcx

###Licenses POST
POST http://localhost:1234/api/licenses
content-type: application/json

[
  {
    "name": "001278Xc",
    "email": "ana@example.com",
    "rol": "Admin",
    "age": 30
  },
  {
    "name": "001278XB",
    "email": "ana@example.com",
    "rol": "Admin",
    "age": 31
  }
]

###Licenses DELETE
DELETE http://localhost:1234/api/licenses/65390d82facded930b3d6f61