###Probar el metodo GET /
GET http://localhost:1234/

###Llamar al metodo /user para obtener lsta de usuarios
GET http://localhost:1234/api/users

###Llamar al metodo /user para obtener lsta de usuarios que tengan el rol Admin
GET http://localhost:1234/api/users?rol=Admin&age=28

###Llamar al metodo /user/id para obtener un usuari
GET http://localhost:1234/api/users/64f0eaa81f8b53690a62c387

###Probar el metodo PUT user para insertar
POST http://localhost:1234/api/users
content-type: application/json

{
  "name": "Ana García",
  "email": "ana@example.com",
  "rol": "Admin",
  "age": 30
}

###Probar el metodo PATCH user para editar
PATCH  http://localhost:1234/api/users/64f0eaa81f8b53690a62c38c
content-type: application/json

{
      "name": "editado2",
      "email": "editado",
      "rol": "Admin",
      "age": 100
}

###Probar el metodo DELETE user para borrar
DELETE http://localhost:1234/api/users/64f0eaa81f8b53690a62c38c
